// NINA — catálogo de cursos e pesos das áreas do ENEM
// Os pesos dos cursos da UFAC vêm do documento OFICIAL:
// "Anexo 2 — Pesos e Notas Mínimas" (SISU/UFAC) — www3.ufac.br/prograd/sisu-2025
// Escala: 3 = peso máximo | 2 = médio | 1 = baixo
// Áreas: linguagens · humanas · natureza · matematica · redacao

const CURSOS = [
  // ==========================================================
  // UFAC — CAMPUS RIO BRANCO (pesos oficiais)
  // ==========================================================
  { id: "ufac-ciencias-biologicas", nome: "Ciências Biológicas", icone: "🧬", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 563.9,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Vida, ecologia, pesquisa e ensino de biologia." },
  { id: "ufac-ciencias-contabeis", nome: "Ciências Contábeis", icone: "🧾", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 656.9,
    pesos: { redacao: 2, natureza: 1, humanas: 2, linguagens: 2, matematica: 3 },
    descricao: "Números, finanças, organização e prestação de contas." },
  { id: "ufac-ciencias-economicas", nome: "Ciências Econômicas", icone: "💰", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 641.9,
    pesos: { redacao: 2, natureza: 1, humanas: 2, linguagens: 2, matematica: 3 },
    descricao: "Matemática, história, atualidades e análise de dados." },
  { id: "ufac-ciencias-sociais", nome: "Ciências Sociais", icone: "👥", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado e Licenciatura", corte: 582.2,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Sociedade, cultura, política e pensamento crítico." },
  { id: "ufac-direito", nome: "Direito", icone: "⚖️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 682.1,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Leitura, argumentação, história e atualidades." },
  { id: "ufac-educacao-fisica-bach", nome: "Educação Física", icone: "🏃", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 581.8,
    pesos: { redacao: 1, natureza: 3, humanas: 2, linguagens: 1, matematica: 1 },
    descricao: "Corpo humano, saúde, esporte e treinamento." },
  { id: "ufac-educacao-fisica-lic", nome: "Educação Física", icone: "🏃", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 581.8,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Corpo, movimento, saúde e ensino." },
  { id: "ufac-enfermagem", nome: "Enfermagem", icone: "💉", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 667.3,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Cuidado, saúde, biologia e relação humana." },
  { id: "ufac-agronomia", nome: "Engenharia Agronômica", icone: "🌱", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 566.6,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Agropecuária, solo, plantas e meio ambiente." },
  { id: "ufac-eng-civil", nome: "Engenharia Civil", icone: "🏗️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 659.5,
    pesos: { redacao: 1, natureza: 2, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Cálculo, física, materiais e construção." },
  { id: "ufac-eng-eletrica", nome: "Engenharia Elétrica", icone: "⚡", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 634.1,
    pesos: { redacao: 1, natureza: 2, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Eletricidade, cálculo, física e tecnologia." },
  { id: "ufac-eng-florestal", nome: "Engenharia Florestal", icone: "🌳", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 534.8,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Floresta, biodiversidade e sustentabilidade." },
  { id: "ufac-filosofia", nome: "Filosofia", icone: "🤔", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 559.8,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Pensamento crítico, ética e argumentação." },
  { id: "ufac-fisica", nome: "Física", icone: "⚛️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado e Licenciatura", corte: 562.7,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Fenômenos, cálculo, experimentação e geofísica." },
  { id: "ufac-geografia-bach", nome: "Geografia", icone: "🗺️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 530.8,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 2, matematica: 1 },
    descricao: "Espaço, clima, mapas e questões socioambientais." },
  { id: "ufac-geografia-lic", nome: "Geografia", icone: "🗺️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 530.8,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 2, matematica: 1 },
    descricao: "Espaço, sociedade e ensino de geografia." },
  { id: "ufac-historia-bach", nome: "História", icone: "🏛️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 562.9,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Contextos históricos, fontes e pesquisa." },
  { id: "ufac-historia-lic", nome: "História", icone: "🏛️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura (Matutino/Noturno)", corte: 562.9,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "História, cidadania e ensino." },
  { id: "ufac-jornalismo", nome: "Jornalismo", icone: "📰", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 616.8,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Escrita, atualidades, interpretação e comunicação." },
  { id: "ufac-letras-espanhol", nome: "Letras — Espanhol", icone: "🇪🇸", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Língua espanhola, literatura e ensino." },
  { id: "ufac-letras-frances", nome: "Letras — Francês", icone: "🇫🇷", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Língua francesa, literatura e ensino." },
  { id: "ufac-letras-ingles", nome: "Letras — Inglês", icone: "🇬🇧", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Língua inglesa, literatura e ensino." },
  { id: "ufac-letras-libras", nome: "Letras — Libras", icone: "🤟", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Língua brasileira de sinais, inclusão e ensino." },
  { id: "ufac-letras-portugues", nome: "Letras — Língua Portuguesa", icone: "📖", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Literatura, gramática, leitura e escrita." },
  { id: "ufac-matematica", nome: "Matemática", icone: "➗", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 598.4,
    pesos: { redacao: 1, natureza: 2, humanas: 1, linguagens: 3, matematica: 3 },
    descricao: "Raciocínio lógico, álgebra, geometria e ensino." },
  { id: "ufac-medicina-veterinaria", nome: "Medicina Veterinária", icone: "🐾", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 659.9,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Animais, biologia, saúde e clínica." },
  { id: "ufac-musica", nome: "Música", icone: "🎵", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 556.8,
    pesos: { redacao: 2, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Percepção sonora, cultura e ensino de música." },
  { id: "ufac-nutricao", nome: "Nutrição", icone: "🥗", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 642,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Alimentação, biologia, química e saúde." },
  { id: "ufac-pedagogia", nome: "Pedagogia", icone: "👩‍🏫", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 577.9,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Educação, leitura, escrita e sociedade." },
  { id: "ufac-psicologia", nome: "Psicologia", icone: "🧠", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 659.8,
    pesos: { redacao: 1, natureza: 3, humanas: 3, linguagens: 2, matematica: 1 },
    descricao: "Comportamento, ciências humanas e biológicas." },
  { id: "ufac-quimica", nome: "Química", icone: "⚗️", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Licenciatura", corte: 537.7,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Matéria, reações, cálculo e experimentação." },
  { id: "ufac-saude-coletiva", nome: "Saúde Coletiva", icone: "🏥", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 539.2,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Saúde pública, prevenção e políticas sociais." },
  { id: "ufac-sistemas-informacao", nome: "Sistemas de Informação", icone: "💻", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado", corte: 658.4,
    pesos: { redacao: 1, natureza: 2, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Tecnologia, lógica, dados e sistemas." },
  { id: "ufac-teatro", nome: "Teatro", icone: "🎭", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado e Licenciatura", corte: 529.4,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Expressão, corpo, texto dramático e cultura." },
  { id: "ufac-medicina", nome: "Medicina", icone: "🩺", grupo: "UFAC · Campus Rio Branco", ufac: true, campus: "Rio Branco", grau: "Bacharelado",
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 1, matematica: 3 },
    descricao: "Biologia, química, física e raciocínio lógico." },

  // ==========================================================
  // UFAC — CAMPUS FLORESTA (Cruzeiro do Sul) — pesos oficiais
  // ==========================================================
  { id: "ufac-czs-biologia-bach", nome: "Ciências Biológicas", icone: "🧬", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Bacharelado", corte: 563.9,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Vida, ecologia e pesquisa científica." },
  { id: "ufac-czs-biologia-lic", nome: "Ciências Biológicas", icone: "🧬", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Licenciatura", corte: 563.9,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Biologia e ensino de ciências." },
  { id: "ufac-czs-direito", nome: "Direito", icone: "⚖️", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Bacharelado", corte: 682.1,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Leitura, argumentação, história e atualidades." },
  { id: "ufac-czs-enfermagem", nome: "Enfermagem", icone: "💉", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Bacharelado", corte: 667.3,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Cuidado, saúde e biologia." },
  { id: "ufac-czs-agronomia", nome: "Engenharia Agronômica", icone: "🌱", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Bacharelado", corte: 566.6,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Agropecuária, solo e meio ambiente." },
  { id: "ufac-czs-florestal", nome: "Engenharia Florestal", icone: "🌳", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Bacharelado", corte: 534.8,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 2, matematica: 1 },
    descricao: "Floresta, biodiversidade e sustentabilidade." },
  { id: "ufac-czs-letras-espanhol", nome: "Letras — Espanhol", icone: "🇪🇸", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Língua espanhola e ensino." },
  { id: "ufac-czs-letras-ingles", nome: "Letras — Inglês", icone: "🇬🇧", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Língua inglesa e ensino." },
  { id: "ufac-czs-letras-portugues", nome: "Letras — Língua Portuguesa", icone: "📖", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Licenciatura", corte: 540,
    pesos: { redacao: 1, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Literatura, gramática e escrita." },
  { id: "ufac-czs-pedagogia", nome: "Pedagogia", icone: "👩‍🏫", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Licenciatura", corte: 577.9,
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Educação, leitura e sociedade." },
  { id: "ufac-indigena", nome: "Licenciatura Indígena", icone: "🪶", grupo: "UFAC · Campus Floresta (Cruzeiro do Sul)", ufac: true, campus: "Cruzeiro do Sul", grau: "Licenciatura",
    pesos: { redacao: 1, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Formação de professores indígenas e saberes tradicionais." },

  // ==========================================================
  // OUTRAS UNIVERSIDADES (referência para quem mira fora do Acre)
  // ==========================================================
  { id: "medicina", nome: "Medicina", icone: "🩺", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 2, natureza: 3, humanas: 1, linguagens: 1, matematica: 3 },
    descricao: "Biologia, química, física e raciocínio lógico." },
  { id: "odontologia", nome: "Odontologia", icone: "🦷", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 1, matematica: 2 },
    descricao: "Biologia, química e ciências da saúde." },
  { id: "fisioterapia", nome: "Fisioterapia", icone: "🦴", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 3, humanas: 2, linguagens: 1, matematica: 2 },
    descricao: "Corpo humano, movimento e reabilitação." },
  { id: "farmacia", nome: "Farmácia", icone: "💊", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 1, matematica: 2 },
    descricao: "Química, biologia e saúde." },
  { id: "biomedicina", nome: "Biomedicina", icone: "🔬", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 3, humanas: 1, linguagens: 1, matematica: 2 },
    descricao: "Pesquisa, biologia e análises clínicas." },
  { id: "servico-social", nome: "Serviço Social", icone: "🤝", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 2, natureza: 1, humanas: 3, linguagens: 2, matematica: 1 },
    descricao: "Questões sociais, políticas públicas e direitos." },
  { id: "relacoes-internacionais", nome: "Relações Internacionais", icone: "🌐", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 2, natureza: 1, humanas: 3, linguagens: 3, matematica: 1 },
    descricao: "Idiomas, geopolítica e atualidades." },
  { id: "publicidade", nome: "Publicidade e Propaganda", icone: "📢", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 3, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Criatividade, comunicação e comportamento." },
  { id: "cinema", nome: "Cinema e Audiovisual", icone: "🎬", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 2, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Narrativa, imagem, som e cultura." },
  { id: "artes-visuais", nome: "Artes Visuais", icone: "🎨", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 2, natureza: 1, humanas: 2, linguagens: 3, matematica: 1 },
    descricao: "Leitura de imagens, história da arte e criação." },
  { id: "design", nome: "Design", icone: "🖌️", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 1, humanas: 1, linguagens: 2, matematica: 2 },
    descricao: "Criatividade, forma, cor e tecnologia." },
  { id: "arquitetura", nome: "Arquitetura e Urbanismo", icone: "📐", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 2, humanas: 2, linguagens: 2, matematica: 3 },
    descricao: "Desenho, matemática, arte e cidade." },
  { id: "administracao", nome: "Administração", icone: "📈", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 2, natureza: 1, humanas: 2, linguagens: 2, matematica: 3 },
    descricao: "Gestão, matemática e comunicação." },
  { id: "ciencia-computacao", nome: "Ciência da Computação", icone: "🖥️", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 1, humanas: 1, linguagens: 2, matematica: 3 },
    descricao: "Lógica, matemática e programação." },
  { id: "eng-computacao", nome: "Engenharia da Computação", icone: "💻", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 2, humanas: 1, linguagens: 1, matematica: 3 },
    descricao: "Matemática, lógica e tecnologia." },
  { id: "estatistica", nome: "Estatística", icone: "📉", grupo: "Outras universidades", ufac: false,
    pesos: { redacao: 1, natureza: 1, humanas: 1, linguagens: 1, matematica: 3 },
    descricao: "Dados, probabilidade e análise." },
];

const GRUPOS_CURSOS = [
  "UFAC · Campus Rio Branco",
  "UFAC · Campus Floresta (Cruzeiro do Sul)",
  "Outras universidades",
];

const ROTULOS_PESO = {
  linguagens: "Linguagens",
  humanas: "Humanas",
  natureza: "Natureza",
  matematica: "Matemática",
  redacao: "Redação",
};

// Lista as áreas de maior peso de um curso (maior peso primeiro)
function areasDePeso(curso) {
  if (!curso || !curso.pesos) return [];
  return Object.entries(curso.pesos)
    .sort((a, b) => b[1] - a[1])
    .map(([area, peso]) => ({ area, peso, nome: ROTULOS_PESO[area] || area }));
}

// Link oficial das notas de corte do SISU (para consulta)
const LINK_CORTE_SISU = "https://acessounico.mec.gov.br/sisu";

if (typeof module !== "undefined") {
  module.exports = { CURSOS, GRUPOS_CURSOS, ROTULOS_PESO, areasDePeso, LINK_CORTE_SISU };
}
