// NINA — Fichário de Encenação (Jogos Teatrais)
// Baseado na obra "Jogos Teatrais: o fichário de Viola Spolin"
// (Viola Spolin; trad. Ingrid Dormien Koudela — Perspectiva).
// Estrutura da ficha original: FOCO · DESCRIÇÃO · INSTRUÇÃO · AVALIAÇÃO · NOTAS · ÁREAS.
//
// ⚠️ JOGO PRESENCIAL: precisa ser conduzido pelo(a) professor(a) na sala.
// Os enunciados de INSTRUÇÃO são para o professor falar DURANTE o jogo.

const ENCENACAO_CATEGORIAS = [
  "Aquecimento",
  "Jogos de Espelho",
  "Onde · Quem · O Quê",
  "Criação Coletiva",
  "Atenção e Sentidos",
  "Improvisação de Cena",
];

const ENCENACAO = [
  // ---------------- AQUECIMENTO ----------------
  {
    nome: "Sentindo o Eu com o Eu",
    categoria: "Aquecimento",
    jogadores: "Grupo todo",
    duracao: "5 min",
    foco: "Sentir o próprio corpo parado, sem fazer nada.",
    descricao: "Fiquem em pé, espalhados pela sala, sem falar e sem fazer nada. Só sintam o próprio corpo e o espaço ao redor.",
    instrucao: [
      "Fiquem parados. Não façam nada.",
      "Sintam os pés no chão.",
      "Percebam o peso do corpo.",
      "Não se preocupem com quem está olhando.",
    ],
    avaliacao: ["O que você sentiu?", "Ficou difícil ficar parado? Por quê?"],
    notas: "Costuma causar desconforto no início — é justamente o ponto. Na segunda vez, dê uma tarefa simples (contar as cadeiras da sala) para mostrar como o FOCO diminui o desconforto.",
    areas: "Teatro, Artes, Educação Física",
    material: "Nenhum",
    espaco: "Sala livre",
  },
  {
    nome: "Visão Periférica",
    categoria: "Aquecimento",
    jogadores: "Grupo todo",
    duracao: "5 a 10 min",
    foco: "Ampliar o campo de visão sem virar a cabeça.",
    descricao: "Olhem para um ponto à frente e, sem mexer a cabeça, percebam o que está nas laterais. Depois andem pela sala mantendo a visão ampla.",
    instrucao: [
      "Olhos num ponto à frente. Sem virar a cabeça.",
      "Percebam quem está à sua direita e à sua esquerda.",
      "Agora andem devagar, sem esbarrar em ninguém.",
      "Continuem vendo o que está nas laterais.",
    ],
    avaliacao: ["Você conseguiu ver as laterais?", "Você esbarrou em alguém?"],
    notas: "Excelente para turmas grandes e espaços pequenos: trabalha percepção espacial e cuidado com o outro.",
    areas: "Teatro, Artes, Educação Física",
    material: "Nenhum",
    espaco: "Sala com espaço para o grupo andar",
  },
  {
    nome: "Siga o Seguidor",
    categoria: "Aquecimento",
    jogadores: "Grupo todo (em duplas)",
    duracao: "5 a 10 min",
    foco: "Alternar liderança e seguimento sem combinar.",
    descricao: "Em duplas, um começa liderando o movimento e o outro copia. Sem falar e sem combinar, a liderança troca de vez em quando.",
    instrucao: [
      "Um lidera, o outro copia.",
      "Não falem. Deixem a troca acontecer.",
      "Quem está seguindo pode assumir a liderança.",
      "Continuem juntos, como se fossem um só.",
    ],
    avaliacao: ["Você percebeu quando a liderança trocou?", "Foi mais fácil liderar ou seguir?"],
    notas: "A troca deve ser natural — se os alunos combinarem 'agora é sua vez', perde o jogo. Reforce o FOCO.",
    areas: "Teatro, Artes, Educação Física",
    material: "Nenhum",
    espaco: "Sala livre",
  },
  {
    nome: "Jogo dos Seis Nomes",
    categoria: "Aquecimento",
    jogadores: "6 a 20",
    duracao: "5 min",
    foco: "Atenção e memória dos nomes do grupo.",
    descricao: "Em círculo, cada pessoa fala o próprio nome. Depois, um começa dizendo o nome de um colega e apontando; o escolhido continua.",
    instrucao: [
      "Fale o nome e aponte para a pessoa.",
      "Sem repetir a mesma pessoa duas vezes seguidas.",
      "Rápido! o nome tem que vir antes do dedo.",
    ],
    avaliacao: ["Ficou mais fácil lembrar os nomes?", "O que ajudou a lembrar?"],
    notas: "Ótimo primeiro jogo do ano: além do teatro, cria vínculo na turma.",
    areas: "Teatro, Artes, acolhimento de turma",
    material: "Nenhum",
    espaco: "Círculo de cadeiras",
  },

  // ---------------- JOGOS DE ESPELHO ----------------
  {
    nome: "Onde é o Espelho?",
    categoria: "Jogos de Espelho",
    jogadores: "Em duplas",
    duracao: "5 a 10 min",
    foco: "Perceber a diferença entre TELA e ESPELHO.",
    descricao: "Em duplas frente a frente. Um se move como uma pessoa se olhando no espelho; o outro reflete. Quem reflete deve evitar virar 'tela' (movimento invertido).",
    instrucao: [
      "Você é o espelho: reflete, não imita de costas.",
      "Se ele levanta a mão direita, você levanta a esquerda.",
      "Ande devagar. Não perca o seu parceiro de vista.",
    ],
    avaliacao: ["Em que momento vocês viraram 'tela' em vez de espelho?", "Quem comandou o jogo?"],
    notas: "A dificuldade de inverter o lado é o coração do jogo. Deixe acontecer, discuta depois.",
    areas: "Teatro, Artes, Matemática (simetria), Educação Física",
    material: "Nenhum",
    espaco: "Duplas espalhadas pela sala",
  },
  {
    nome: "Espelho com Fala",
    categoria: "Jogos de Espelho",
    jogadores: "Em duplas",
    duracao: "10 min",
    foco: "Refletir o outro por completo: corpo e fala juntos.",
    descricao: "Agora a dupla pode falar. Um fala e se movimenta, o outro reflete fala e movimento ao mesmo tempo, sem atraso.",
    instrucao: [
      "Reflitam a fala, não respondam.",
      "Não é conversa: é espelho.",
      "Juntos: corpo e voz.",
    ],
    avaliacao: ["Quando vocês deixaram de refletir e passaram a conversar?", "Como foi não poder responder?"],
    notas: "Muitos alunos vão querer virar conversa — esse é o objetivo da avaliação.",
    areas: "Teatro, Artes, Língua Portuguesa (escuta)",
    material: "Nenhum",
    espaco: "Duplas espalhadas",
  },

  // ---------------- ONDE · QUEM · O QUÊ ----------------
  {
    nome: "Jogo do ONDE",
    categoria: "Onde · Quem · O Quê",
    jogadores: "Times de 2 a 5",
    duracao: "15 min",
    foco: "Mostrar onde a cena acontece (ambiente), sem dizer o nome do lugar.",
    descricao: "Cada time improvisa uma cena curta. O grupo que assiste deve descobrir ONDE a cena acontece, usando apenas o que o corpo faz com o ambiente.",
    instrucao: [
      "Usem os objetos imaginários do lugar.",
      "O corpo conta onde é. Não falem o nome do lugar.",
      "Se é uma cozinha, mexam na panela; se é um rio, remem.",
    ],
    avaliacao: ["Descobrimos o lugar?", "O que mostrou o lugar: o corpo ou a fala?"],
    notas: "Comece pelo ONDE porque é o mais concreto. Só libere a fala depois que o ambiente estiver claro.",
    areas: "Teatro, Artes, Geografia (espaço)",
    material: "Nenhum (objetos imaginários)",
    espaco: "Área de cena + plateia",
  },
  {
    nome: "Jogo do QUEM",
    categoria: "Onde · Quem · O Quê",
    jogadores: "Times de 2 a 5",
    duracao: "15 min",
    foco: "Criar personagem e relação sem explicar quem é.",
    descricao: "Cada time improvisa definindo QUEM são (idade, profissão, relação entre eles). A plateia descobre pelo comportamento, não pela fala explicativa.",
    instrucao: [
      "Mostrem a relação pelo jeito de falar e de olhar.",
      "Nada de dizer 'eu sou o pai dela'.",
      "Como essa pessoa anda? Como fala?",
    ],
    avaliacao: ["Quem eram? Como descobrimos?", "O que foi mais forte: o corpo ou a voz?"],
    notas: "Sugira relações simples: mãe e filho, cobrador e devedor, professora e aluno.",
    areas: "Teatro, Artes, Sociologia (relações)",
    material: "Nenhum",
    espaco: "Área de cena + plateia",
  },
  {
    nome: "Jogo do O QUÊ",
    categoria: "Onde · Quem · O Quê",
    jogadores: "Times de 2 a 5",
    duracao: "15 min",
    foco: "Sustentar uma atividade real durante a cena.",
    descricao: "Cada time recebe uma tarefa concreta (plantar, coser, cozinhar, consertar uma rede). A cena só acontece enquanto a tarefa está sendo feita de verdade.",
    instrucao: [
      "Façam a tarefa de verdade, passo a passo.",
      "A tarefa é o foco, não a conversa.",
      "Se perderem a tarefa, recomecem.",
    ],
    avaliacao: ["A tarefa foi feita até o fim?", "Quando vocês esqueceram o que estavam fazendo?"],
    notas: "Objetos imaginários exigem concentração. Ótimo para turmas agitadas: o FOCO acalma.",
    areas: "Teatro, Artes, Educação para o trabalho",
    material: "Nenhum",
    espaco: "Área de cena + plateia",
  },
  {
    nome: "Parte de um Todo",
    categoria: "Criação Coletiva",
    jogadores: "Grupo todo",
    duracao: "10 a 15 min",
    foco: "Cada um é uma parte de uma coisa só.",
    descricao: "O grupo constrói junto um objeto ou lugar (um carro, uma floresta, uma escola) usando o corpo de cada um como parte do todo.",
    instrucao: [
      "Cada pessoa é uma parte. Qual é a sua?",
      "Encaixem-se sem se tocar.",
      "Encontrem o movimento comum do todo.",
    ],
    avaliacao: ["Que todo vocês formaram?", "Sua parte funcionava sozinha?"],
    notas: "Excelente para mostrar que teatro é trabalho coletivo.",
    areas: "Teatro, Artes, Biologia (sistemas), interdisciplinar",
    material: "Nenhum",
    espaco: "Sala ampla",
  },
  {
    nome: "Máquina",
    categoria: "Criação Coletiva",
    jogadores: "Grupo todo",
    duracao: "10 min",
    foco: "Ritmo e repetição coletiva.",
    descricao: "Um por vez entra no espaço e escolhe um movimento e um som, repetindo sem parar. Cada novo participante encaixa seu movimento na máquina.",
    instrucao: [
      "Repitam sempre o mesmo movimento e o mesmo som.",
      "Encaixem o seu ritmo no do coletivo.",
      "A máquina não para.",
    ],
    avaliacao: ["A máquina funcionava junta?", "Quem acelerou o ritmo?"],
    notas: "Começa com 3 pessoas e vai somando. Se a máquina quebrar, reinicie com calma.",
    areas: "Teatro, Artes, Música (ritmo), Física (movimento)",
    material: "Nenhum",
    espaco: "Sala ampla",
  },

  // ---------------- ATENÇÃO E SENTIDOS ----------------
  {
    nome: "Jogos de Olhar",
    categoria: "Atenção e Sentidos",
    jogadores: "Em duplas ou grupo",
    duracao: "5 a 10 min",
    foco: "Ver de verdade: detalhe antes do julgamento.",
    descricao: "Em duplas, observem o colega por 30 segundos. Depois fechem os olhos e descrevam, em detalhes, o que viram — sem opinião, só o que existe.",
    instrucao: [
      "Olhe. Só olhe.",
      "Agora de olhos fechados: descreva o que viu.",
      "Sem 'bonito' ou 'feio': só o que está lá.",
    ],
    avaliacao: ["Quantos detalhes você lembrou?", "Você olhou de verdade ou só passou o olho?"],
    notas: "Ligação direta com a leitura de imagens em Artes.",
    areas: "Teatro, Artes (leitura de imagem), Ciências (observação)",
    material: "Nenhum",
    espaco: "Duplas",
  },
  {
    nome: "Jogos de Ouvir",
    categoria: "Atenção e Sentidos",
    jogadores: "Grupo todo",
    duracao: "5 a 10 min",
    foco: "Escutar os sons do ambiente antes dos sons da sala.",
    descricao: "Todos fecham os olhos por 1 minuto e escutam. Depois, cada um diz um som que ouviu, do mais distante ao mais próximo.",
    instrucao: [
      "Olhos fechados. Escutem.",
      "Qual som vem de fora da sala?",
      "Qual som vem de dentro do seu próprio corpo?",
    ],
    avaliacao: ["Que sons vocês só ouviram depois de ficar quietos?", "Escutar é diferente de esperar a vez de falar?"],
    notas: "Ótimo aquecimento para trabalhar escuta em diálogos e em Língua Portuguesa.",
    areas: "Teatro, Artes, Música, Língua Portuguesa",
    material: "Nenhum",
    espaco: "Sala silenciosa",
  },
  {
    nome: "Jogo de Identificação",
    categoria: "Atenção e Sentidos",
    jogadores: "Grupo todo",
    duracao: "5 a 10 min",
    foco: "Reconhecer o outro pelo toque ou pela voz.",
    descricao: "Uma pessoa de olhos vendados fica no centro. Os colegas passam, um a um, e ela deve identificar quem passou (pelo toque na mão ou pela voz).",
    instrucao: [
      "Só a mão ou a voz. Sem espiar.",
      "Quem passar, não pode rir nem imitar.",
      "Concentre-se no detalhe que identifica a pessoa.",
    ],
    avaliacao: ["O que fez você reconhecer?", "Foi mais fácil pela voz ou pelo toque?"],
    notas: "Combine antes que ninguém será forçado a participar. Respeite quem não quiser.",
    areas: "Teatro, Artes, Educação Física",
    material: "Uma venda (lenço)",
    espaco: "Círculo",
  },
  {
    nome: "Jogo do Vocabulário",
    categoria: "Atenção e Sentidos",
    jogadores: "Times",
    duracao: "10 min",
    foco: "Mostrar uma palavra sem usar essa palavra.",
    descricao: "O professor dá uma palavra ou expressão. O time improvisa uma cena curta que mostre o sentido dela, sem falar a palavra.",
    instrucao: [
      "Não digam a palavra. Mostrem.",
      "Usem o corpo, o ambiente e a relação entre vocês.",
      "A plateia tem que adivinhar a palavra.",
    ],
    avaliacao: ["Acertamos a palavra?", "O que ficou claro e o que não ficou?"],
    notas: "Excelente ponte com Língua Portuguesa: sinônimos, expressões, regionalismos (ótimo com o Dicionário Acreanês!).",
    areas: "Teatro, Artes, Língua Portuguesa",
    material: "Lista de palavras",
    espaco: "Área de cena + plateia",
  },

  // ---------------- IMPROVISAÇÃO DE CENA ----------------
  {
    nome: "Contato",
    categoria: "Improvisação de Cena",
    jogadores: "Em duplas",
    duracao: "10 min",
    foco: "Construir uma cena a partir de um ponto de contato (de olhar ou de toque).",
    descricao: "Duplas começam a cena a partir de um contato definido (de mãos dadas, frente a frente, de costas). A cena precisa nascer desse encontro.",
    instrucao: [
      "Mantenham o contato. Não soltem.",
      "A cena nasce do encontro, não do texto.",
      "Onde vocês estão? Quem são?",
    ],
    avaliacao: ["O contato ajudou ou atrapalhou a cena?", "Quando vocês esqueceram o contato?"],
    notas: "Aproxima a turma e trabalha limites: combine antes que o toque é sempre respeitoso e opcional.",
    areas: "Teatro, Artes, convivência",
    material: "Nenhum",
    espaco: "Duplas espalhadas",
  },
  {
    nome: "Jogo do Tempo",
    categoria: "Improvisação de Cena",
    jogadores: "Times",
    duracao: "15 min",
    foco: "Perceber a passagem do tempo na cena.",
    descricao: "A mesma cena é improvisada três vezes: em ritmo lento, normal e acelerado. O time sente como o tempo muda a história.",
    instrucao: [
      "Agora em câmera lenta.",
      "Agora no ritmo do dia a dia.",
      "Agora correndo, mas sem perder o ONDE.",
    ],
    avaliacao: ["O que mudou na história quando o tempo mudou?", "Qual ritmo ficou mais verdadeiro?"],
    notas: "Faz o aluno perceber que ritmo é escolha, não acaso.",
    areas: "Teatro, Artes, Física (tempo), Música (andamento)",
    material: "Nenhum",
    espaco: "Área de cena",
  },
  {
    nome: "Jogo dos Contos",
    categoria: "Improvisação de Cena",
    jogadores: "Grupo todo",
    duracao: "15 a 20 min",
    foco: "Construir uma história coletiva, um pedaço por vez.",
    descricao: "Em círculo, cada pessoa acrescenta uma frase à história. Depois, o grupo encena a história criada.",
    instrucao: [
      "Cada um diz uma frase. Não pulem a vez.",
      "Ouçam o que veio antes para continuar.",
      "Depois, vamos encenar o que criamos.",
    ],
    avaliacao: ["A história faz sentido?", "Como cada um ajudou na história do outro?"],
    notas: "Ligação forte com literatura e com a tradição oral acreana e amazônica.",
    areas: "Teatro, Artes, Literatura, História (oralidade)",
    material: "Nenhum",
    espaco: "Círculo, depois área de cena",
  },
  {
    nome: "Exposição de Problemas",
    categoria: "Improvisação de Cena",
    jogadores: "Times",
    duracao: "20 min",
    foco: "Resolver um problema dramático em cena, sem combinar a solução.",
    descricao: "O professor apresenta um problema (uma ponte caiu, faltou água, alguém se perdeu na floresta). O time improvisa e resolve junto, na hora.",
    instrucao: [
      "O problema é real para vocês agora.",
      "Resolvam juntos, não um por um.",
      "Onde vocês estão? Quem são? Qual é a urgência?",
    ],
    avaliacao: ["O problema foi resolvido?", "Alguém ficou de fora da solução?"],
    notas: "É o jogo mais rico para temas sociais, ambientais e do cotidiano acreano (cheia, queimada, seca dos rios).",
    areas: "Teatro, Artes, temas transversais, Ciências do ambiente",
    material: "Nenhum",
    espaco: "Área de cena + plateia",
  },
  {
    nome: "Transformação de Objeto",
    categoria: "Improvisação de Cena",
    jogadores: "Grupo todo",
    duracao: "10 min",
    foco: "Transformar um objeto imaginário sem perder a sua forma física.",
    descricao: "Um objeto imaginário (uma bola, um bastão) passa de mão em mão. Cada um o transforma em outra coisa, mantendo o peso e o tamanho.",
    instrucao: [
      "Segure o peso do objeto real.",
      "Transforme: agora é um telefone, depois uma panela.",
      "Mantenha o tamanho que a pessoa antes deixou.",
    ],
    avaliacao: ["O objeto manteve o mesmo peso?", "Quando a transformação perdeu a lógica?"],
    notas: "Fundamental para a leitura de imagens e para a abstração em Artes Visuais.",
    areas: "Teatro, Artes Visuais, criação",
    material: "Nenhum",
    espaco: "Círculo",
  },
];

if (typeof module !== "undefined") {
  module.exports = { ENCENACAO, ENCENACAO_CATEGORIAS };
}
